### ISSUE TITLE
Retina loga - optimalizace

### ISSUE THREAD

**Issue by klokan** [klokan/old.maptiler.com#10]
Loga na strance na Retina display vypadaji docela priserne.
Prosim pouzijte 2x rozmery pro obrazky.

**Comment by robertsolarik** [comment]
Ahoj, pozeral som na na tie loga, ale ani v PSD ktoré mám k dispozícii (klokantech-design-concept-02-1.psd) nie sú použité smart objects, ktoré z ktorých by som si mohol vyššie rozlíšenie zobrať. (Dokonca hlavné logo Klokantech je aj v PSD zväčšené na 218% proti originálu.) 

Prosím o poslanie PSD s jednotlivými logami v nejakom rozumnom rozlíšení (ideálne nech je to vektor), aby som ich mohol vymeniť. Ďakujem

**Comment by klokan** [comment]
Spoj se prosim s Radimem - viz radim.kacer@klokantech.com @radimkacer

**Comment by klokan** [comment]
Old Maps Online jeste neni v retina - ale neni to klicove. Zaviram ticket, diky.
