### ISSUE TITLE
mobile-apps.html page

### ISSUE THREAD

**Issue by scootland** [klokan/old.maptiler.com#2]
Please fix lines in the left column of this file and post it

**Comment by robertsolarik** [comment]
Can not find mobile-apps.html. Where is it located?

**Comment by scootland** [comment]
mám to tu lokálnì ale nemù¾u se domluvit s tím push/pull, poøád mi to pí¹e
nìjaké errory a kdovíco, posílám Ti to mailem..

**Comment by robertsolarik** [comment]
Opravené, commitnuté a pushnuté...

**Comment by scootland** [comment]
V pořádku. Peťo, můžeš to prosím nahrát na www.maptiler.com - aby to bylo online?

**Comment by klokan** [comment]
Duplicate to new https://github.com/klokan/www.maptiler.com/issues/11
