### ISSUE TITLE
Klokantech.com - mainpage

### ISSUE THREAD

**Issue by scootland** [klokan/old.maptiler.com#3]
Do mainpage according to mockup
![klokantech-design-concept-04](https://f.cloud.github.com/assets/2953502/1500842/40e1ef9e-4881-11e3-9f63-4eb1c0d1c564.jpg)
![klokantech-design-concept-05](https://f.cloud.github.com/assets/2953502/1500843/40e2923c-4881-11e3-9bed-67e37357efb3.jpg)

**Comment by robertsolarik** [comment]
Commitol a pushol som prvé zmeny na úvodnú stránku. 
- Zachoval som horný panel tak ako je na maptiler.com aby bola zachovaná konzistencia. 
- Zväčšil som logo klokantech a umiestnil do stredu
- Hlavný banner som dal na šedé pozadie aby tvorilo určitý kontrast
- Tri stĺpce a blok s oldmaps podľa grafického návrhu.
- Menu sa pri scrollovaní prilepí na vrch stránky podobne ako pri maptiles.com.

http://maptiler.github.io/www.maptiler.com/klokantech.html

Celkovo som mi to trvalo 3 hodiny (vrátane nejakej úvodnej orientácie v kóde)

Prosím o kontrolu

**Comment by scootland** [comment]
Čau, zbývá doladit:
- fonty
- lišta odkazů (šedé pozadí)
- scrollování - tak aby nezůstávalo menu nahoře ale scrollovalo se to celé
- hlavičku dle návrhu (přiloženo)

![klokantech-design-concept-09](https://f.cloud.github.com/assets/2953502/1535538/74091d52-4ca5-11e3-8b6f-d917108a7e54.jpg)

**Comment by robertsolarik** [comment]
- lišta odkazů (šedé pozadí) - zapracované, ale výšku som nechal tak ako bola (definované v šablóne) a aj aktívne položky som nechal tak ako boli pôsovne myslené - s modrou linkou hore a nie celo podfarbené (môžeme samozrejme zmeniť)
- scrollování - tak aby nezůstávalo menu nahoře ale scrollovalo se to celé - Opravené
- hlavičku dle návrhu (přiloženo) - Opravené

Fonty - neviem čo presne máš na mysli - používajú sa default fonty ako sú definované v šablóne. Môžeme zmeniť, ale potom by bolo dobré aby to bolo rovnaké aj s maptiler.com...

**Comment by scootland** [comment]
fonty tedy nechme. Prosím o:
- odstranění šedého proužku a background komplet v bílé. Oddělit pole
  tenkou šedou čárou, tak jak je v návrhu.
- změnšit výšku šedého proužku nahoře

Už se to pěkně rýsuje :)

2013/11/15 Robert Solarik notifications@github.com

**Comment by robertsolarik** [comment]
Upravená zatiaľ prvá stránka aby čo najvernejšie "kopírovala" PSD grafický návrh. O renderovanie fontov sa stará prehliadač a preto zobrazenie písma nie je rovnaké ako v PSD. Pls pošli mi PSD aj na ostatné stránky. Dík.

**Comment by scootland** [comment]
Radim (grafiko) mi říkal, že by ty ostatní stránky měly být taktéž v tom psd souboru, ve složce klokantech. Já to neotevřu (nemám photoshop), tak nevím...? Zkus mrknout a kdyžtak mi řekni. Případně napiš přímo jemu na email.radim@gmail.com. H.

**Comment by robertsolarik** [comment]
OK, pozriem na to. Musel som ísť dnes do Nitry. Keď sa vrátim tak dokončím
tie ostatné stranky. Zatiaľ prosím napíš nejaký komentár k tej úvodnej
stránke. Dik.  R.
Dňa 22.11.2013 0:52 používateľ "Scootland" notifications@github.com
napísal:

**Comment by scootland** [comment]
Hlavní stránka je úplně OK, nemám připomínek, myslím že hotovo

2013/11/22 Robert Solarik notifications@github.com

**Comment by scootland** [comment]
Drobná změna, skrýt hlavičku a přidat social icons.

![klokantech-design-concept-11](https://f.cloud.github.com/assets/2953502/1621033/cdbeacca-5684-11e3-934a-ff5b4a55529e.jpg)

**Comment by scootland** [comment]
Prosím o dodělání tohtoto ticketu - úplně odstraníme tu hlavičku - horní část s linkou a přidáme social icons. Hlavička bude pryč i na všech podstránkách.

H.

**Comment by robertsolarik** [comment]
Lista skryta na vsetkych strankach aj na blogu

**Comment by klokan** [comment]
Initial implementation deployed. Bugs in separate tickets under https://github.com/klokan/www.klokantech.com/

Closing.
