### ISSUE TITLE
Klokantech.com - company

### ISSUE THREAD

**Issue by scootland** [klokan/old.maptiler.com#4]
text to paste on the webpage:
photo missing at the moment..

Klokan Technologies GmbH was founded in 2010 as a result of almost 10 years of freelance activities of its managing director, Petr Pridal, in the field of online mapping technologies. As an active participant of conferences worldwide, Petr established a network of partners and customers, who share our beliefs in importance of widely accessible culture heritage and maps.

To connect cartographic past with today’s reality is a path on which we set, building on open-source technologies combined with custom development. A vision for personal use of maps by individuals and growing importance of mobile technologies drives us to create easy-to-use software for end users that combine computing power of their devices with simplicity of use.

The company is privately held with headquarters and the main office in Baar, Switzerland. Second office and a part of the development team are located in Brno, Czech republic.  Currently, eight people work for the company and the team actively participates on various research projects internationally and grows with new accepted contracts.

**Comment by scootland** [comment]
Bude ve 3 sloupcích, viz mockup, ještě doplním nadpisy, které teď ještě nemáme

![klokantech-design-concept-07](https://f.cloud.github.com/assets/2953502/1535590/09f2f068-4ca6-11e3-884c-b52d75fa87f9.jpg)

**Comment by robertsolarik** [comment]
Stránku som pripravil, ale zase som pod text "Maps for Poeple. Online." dal také isté tmavé pozadie ako na úvodnej stránke. Podľa mňa to vyzerá lepšie keď je to menu vizuálne oddelené. Medzery medzi stĺpcam sú menšie ako v mockupe pretože používam systém stĺpcov ako je pripravený v šablóne (ak by bolo treba, tak medzery zväčšíme, ale myslím, že to vyzerá dobre). Doplnil som aj nejake ikonky nad text, nech to vyzerá živšie (môžeme zmeniť, resp. dať úplne preč.) Farby som prispôsobil podľa loga.

**Comment by scootland** [comment]
Obecně - držel bych se návrhu, tmavé pozadí určitě ne, stejně tak ikonky. Co chceme je simple, tak ať to je tak jak u návrhu. Zkus to prosím dát takto a na mě pořád visí doplnit ty nadpisy..
