### ISSUE TITLE
Klokantech - blog, projects, customers

### ISSUE THREAD

**Issue by scootland** [klokan/old.maptiler.com#6]
Bude řešeno jako výpis z bloggeru podle labelu. 

blog.klokantech.com

**Comment by scootland** [comment]
posílám mockup

![klokantech-design-concept-08](https://f.cloud.github.com/assets/2953502/1535556/ab092996-4ca5-11e3-8ae6-5cd0bd88e96a.jpg)

**Comment by robertsolarik** [comment]
Nato aby som mohol niečo robiť s designom budem potrebovať nejaké prístupové údaje do bloggeru. Máme aj nejakú kópiu toho blogu aby som zmeny nerobil na živom webe, ale niekde mimo?

**Comment by scootland** [comment]
cau, ohledne loginu mi zavolej a reknu Ti ho do telefonu, kopii musí odpověděť Petr, to já nevím. H.

**Comment by scootland** [comment]
Blog - pořadí menu vpravo

1) Search this blog
2) Blog archive
3) Labels

pak to ostatní, nevím co s followers, jestli mají být úplně nahoře, podle mě to zase tak důležitý údaj není, ale jestli se to tak dělá, tak to tam holt dáme, mohlo by to klidně být menší, nebo to nebýt vůbec, to asi nechám na Tobě..

**Comment by klokan** [comment]
Pokud je template pro blogger pripraven spravne (jako ze stary je) tak poradi techto elementu i vlastni elementy muzes menit primo v administraci blogu - klikanim.

**Comment by scootland** [comment]
Prosím oddělat modré podsvícení datumu - nechat pouze černé písmo na černém podkladu. Zbytek je OK a může se pak uzavřít

**Comment by klokan** [comment]
Je to nekde v preview online?

**Comment by scootland** [comment]
http://klokantechdev.blogspot.sk/

**Comment by robertsolarik** [comment]
Modre podsvietenie je prec - zostal cierny text na bielom pozadi

**Comment by scootland** [comment]
V pořádku, můžeme nasadit

**Comment by klokan** [comment]
Jeste bych mel jednu prosbu:

Vypis normalniho seznamu blog postu ("index" page) a jednotlivych blog postu ("item" page) je ok - a takto by mel zustat. Zrovna zobrazit cely text blog postu.

Vypis pro zvoleny label by mel ale mit kondenzovane zobrazeni - s kratkym textem a jen jednim thumbnailem - aby se ocima dalo prejet celym seznamem - a kdyz budu chtit vedet vic o jednom z postu - tak si na nej kliknu.

Pokud zvolim label "customers", pristanu na strance: http://blog.klokantech.com/search/label/customers
kde bude pro kazdy post jen kratky text a jeden thumbnail (v blogger template jsou dostupne jako `<img expr:src='data:post.thumbnailUrl'/>` a `<data:post.snippet/>`.

Idealne thumbnailUrl nalevo a vpravo od toho ten text snippet. Visuelne se to tedy bude trochu podobat mobilnimu zobrazeni blogu: http://blog.klokantech.com/?m=1

V Blogger template by to melo jit udelat pomoci: http://mystady.com/2011/05/7-blogger-page-types-analysis-code.html#label-page-type tedy:

```
<b:if cond='data:blog.pageType == "index"'>
<b:if cond='data:blog.searchLabel'>
<!--Label Page-->
</b:if>
</b:if>
```

Je to srozumitelne?

**Comment by klokan** [comment]
Initial implementation deployed. Bugs in separate tickets under https://github.com/klokan/www.klokantech.com/
