### ISSUE TITLE
Maptiler.com - request a demo form + pricelist

### ISSUE THREAD

**Issue by scootland** [klokan/old.maptiler.com#7]
V ceníku je u MapTiler Pro pole request a demo. Po kliknutí se musí zobrazit form, kde je třeba, aby potenciální zákazník vyplnil povinná pole:

1) Name
2) Email
3) Company Name
4) Company address
5) Operating system (vybírátko Win, Mac, Linux)
- tam musí být viditelně ke stažení ceník v pdf

![mockup](https://f.cloud.github.com/assets/2953502/1501305/7c55e30c-4889-11e3-9f5a-059ceb6e3dac.png)

**Comment by robertsolarik** [comment]
Zapracovaný design formulára - POZOR! formulár nie je ešte funkčný - nenasadzovať do ostrého prostredia - podobne ako pri kontaktom formulári na novej stránke KlokanTech musíme najskôr zistiť či môžeme použiť napr PHP na odoslanie formulára, alebo použijeme Google App engine ako tomu bolo doteraz (neviem ako to funguje - nerobil som s tým ešte, ale nepredpokladám, že by to mal byť nejaký problém...)

Pri formulári je aj miesto na nejaký text... Prosím o dodanie textu a ja ho tam vymením...

![image](https://f.cloud.github.com/assets/5886415/1550166/94a6f63a-4dfc-11e3-8214-11303c4e1c37.png)

**Comment by scootland** [comment]
Formulář je OK, zajímavé je i řešení s tím že se to tam i objeví, myslím že může být. Určitě je třeba změnit u systémů - Mac OSX. Text bych tam žádný necpal, není třeba. Dej Download pricelist na střed a bude to OK.

**Comment by scootland** [comment]
Můžeme dát již na stránku www.maptiler.com? Je to hotové - stačí jen dopsat login pro posílání mailů a otestovat. Hynda

**Comment by klokan** [comment]
Deployed. Very nice.
