### ISSUE TITLE
Změna hover color

### ISSUE THREAD

**Issue by scootland** [klokan/old.maptiler.com#8]
prosím o změnu hover color pro menu na "ededed" 

Po vybrání zůstává modrá (tak jak je)

díky H.

**Comment by klokan** [comment]
Jeste prosim zadnou diru mezi dvema menu oblastmi - tzn. kdyz hoveruju tak oblast jednoho menu primo navazuje na oblast druheho. Pokud je padding zadouci, tak at je vevnitr oznacene oblasti - nikoliv vne.

**Comment by robertsolarik** [comment]
Už som to asi pochopil - je to opravene :D 
![image](https://f.cloud.github.com/assets/5886415/1881501/14696566-7967-11e3-8ec4-578909afea26.png)

**Comment by scootland** [comment]
Super, diky :)
