### ISSUE TITLE
Hover pro produktové linky

### ISSUE THREAD

**Issue by scootland** [klokan/old.maptiler.com#9]
Prosím modré a underline, jen pro ty 3 odkazy dole (maptiler, georef., mapranksearch)
![klokantech-design-concept-12](https://f.cloud.github.com/assets/2953502/1620925/726cbdf0-5682-11e3-9328-6c59996c9358.jpg)

**Comment by robertsolarik** [comment]
Chcem sa spytat ci by nebolo v ramci konzistentnosti dobre prefarbit na modro aj link www.OldMapsOnline.org
